"""Phase 5 L1 — researcher_actions + session_flags tables.

Per brief §10.1: `researcher_actions` records every researcher-issued
command on a session (force_prompt, whisper, mute, etc.), linking back
to the resulting `decisions` row when the command produced a spoken
intervention. `session_flags` records bookmark moments — either
researcher-flagged via `flag_moment` (brief §5.4) or auto-generated by
the engine for post-session replay surfaces.

Schema notes vs. the brief:

  * `researcher_id` is `uuid NOT NULL` per brief, but stored without an
    FK because the engine doesn't own the Auth.js users table — same
    pattern as `studies.created_by` (see migration 0006 module
    docstring). The engine's domain model carries it as `str` and
    serialises it as a UUID; the column type enforces format at the DB.
  * `session_id` uses `ON DELETE CASCADE` — researcher actions and
    flags belong to a specific session; if that session is purged for
    retention they go with it. Matches the `decisions` table pattern
    (migration 0005).
  * `resulting_decision_id` uses `ON DELETE SET NULL` so a future
    decisions purge job (retention §10.2) can drop rows without
    orphaning the researcher_action — the command itself is the load-
    bearing audit record. Non-spoken commands (mute, pause,
    set_quietness_budget, flag_moment) leave the column null.
  * `(session_id, ts)` index on both tables matches the dashboard's
    "show me everything that happened in this session" query shape.
  * `command_type` is text without a CHECK constraint, mirroring the
    pragmatic decision in migration 0005 to use a Python-side Literal
    as the source of truth and let new command variants land via
    application-only changes. The decisions table got a CHECK because
    a malformed `action` could route audio through the wrong dispatch
    path; for `researcher_actions` the column is purely an audit field.

Revision ID: 0007_researcher_actions_flags
Revises: 0006_studies_table
Create Date: 2026-05-17 01:36:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007_researcher_actions_flags"
down_revision: str | None = "0006_studies_table"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "researcher_actions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "sessions.id",
                ondelete="CASCADE",
                name="fk_researcher_actions_session_id_sessions",
            ),
            nullable=False,
        ),
        sa.Column(
            "researcher_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "ts",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column("command_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=True),
        sa.Column(
            "resulting_decision_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "decisions.id",
                ondelete="SET NULL",
                name="fk_researcher_actions_resulting_decision_id_decisions",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_researcher_actions_session_id_ts",
        "researcher_actions",
        ["session_id", "ts"],
    )

    op.create_table(
        "session_flags",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "sessions.id",
                ondelete="CASCADE",
                name="fk_session_flags_session_id_sessions",
            ),
            nullable=False,
        ),
        sa.Column(
            "ts",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "researcher_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "auto_generated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.create_index(
        "ix_session_flags_session_id_ts",
        "session_flags",
        ["session_id", "ts"],
    )


def downgrade() -> None:
    op.drop_index("ix_session_flags_session_id_ts", table_name="session_flags")
    op.drop_table("session_flags")
    op.drop_index(
        "ix_researcher_actions_session_id_ts",
        table_name="researcher_actions",
    )
    op.drop_table("researcher_actions")
