/**
 * Boundary tests for the flagged audio clip export route.
 *
 * Pins:
 *   - 401 for unauthenticated; never spawns ffmpeg or hits R2.
 *   - 404 when the flag doesn't exist OR belongs to a different session
 *     (cross-session smuggling guard — same defence as the SSE
 *     backfill cursors).
 *   - 404 when the session itself is missing.
 *   - 422 when the session hasn't started or has no composite recording.
 *   - 503 when R2 is not configured for this deployment.
 *   - 200 streams `audio/mpeg` with a sane Content-Disposition; the
 *     R2 URL is signed before ffmpeg is invoked; ffmpeg receives the
 *     correct clip window for the flag's offset from session start.
 */

import { beforeEach, describe, expect, it, vi } from 'vitest';

import type * as ExportsModule from '@/features/exports';
import type { ReplaySessionRow, SessionFlagRow } from '@/features/sessions';

interface MockSession {
  user?: { id: string; email: string } | null;
}

interface FakeScopedSessionRow {
  id: string;
  studyId: string;
  livekitRoomName: string;
  status: string;
  scheduledStart: Date | null;
  actualStart: Date | null;
  actualEnd: Date | null;
  createdAt: Date;
}

const authMock = vi.fn<() => Promise<MockSession | null>>();
const findSessionFlagByIdMock = vi.fn<(id: string) => Promise<SessionFlagRow | null>>();
const findSessionForReplayMock = vi.fn<(id: string) => Promise<ReplaySessionRow | null>>();
const signGetUrlMock = vi.fn<(key: string, ttl?: number) => Promise<string>>();
const spawnFfmpegClipStreamMock = vi.fn<
  (opts: { inputUrl: string; window: { startSec: number; durationSec: number } }) => {
    body: ReadableStream<Uint8Array>;
    done: Promise<number>;
    stderr: Promise<string>;
  }
>();
const scopedSessionsFindByIdMock =
  vi.fn<(sessionId: string) => Promise<FakeScopedSessionRow | null>>();

vi.mock('@/lib/auth', () => ({
  auth: (): Promise<MockSession | null> => authMock(),
}));

vi.mock('@/features/sessions', () => ({
  findSessionFlagById: findSessionFlagByIdMock,
  findSessionForReplay: findSessionForReplayMock,
}));

vi.mock('@/lib/scoped-db', () => ({
  scopedDb: (_orgId: string) => ({
    sessions: {
      findById: scopedSessionsFindByIdMock,
    },
  }),
}));

class FakeR2NotConfiguredError extends Error {
  constructor() {
    super('r2 not configured');
    this.name = 'R2NotConfiguredError';
  }
}

vi.mock('@/features/recordings', () => ({
  signGetUrl: (key: string, ttl?: number): Promise<string> => signGetUrlMock(key, ttl),
  R2NotConfiguredError: FakeR2NotConfiguredError,
}));

vi.mock('@/features/exports', async () => {
  const actual = await vi.importActual<typeof ExportsModule>('@/features/exports');
  return {
    ...actual,
    spawnFfmpegClipStream: (opts: {
      inputUrl: string;
      window: { startSec: number; durationSec: number };
    }): { body: ReadableStream<Uint8Array>; done: Promise<number>; stderr: Promise<string> } =>
      spawnFfmpegClipStreamMock(opts),
  };
});

async function importRoute() {
  return import('./route');
}

function makeContext(id: string, flagId: string) {
  return { params: Promise.resolve({ id, flagId }) };
}

function makeScopedSession(): FakeScopedSessionRow {
  return {
    id: 'sess-12345678abcdef',
    studyId: 'study-1',
    livekitRoomName: 'room-alpha',
    status: 'ended',
    scheduledStart: null,
    actualStart: new Date('2026-05-01T10:00:00.000Z'),
    actualEnd: new Date('2026-05-01T10:30:00.000Z'),
    createdAt: new Date('2026-05-01T09:55:00.000Z'),
  };
}

function makeFlag(overrides: Partial<SessionFlagRow> = {}): SessionFlagRow {
  return {
    id: 'flag-12345678abcdef',
    sessionId: 'sess-12345678abcdef',
    ts: new Date('2026-05-01T10:01:30.000Z'),
    researcherId: 'r-1',
    note: 'come back here',
    autoGenerated: false,
    ...overrides,
  };
}

function makeSession(overrides: Partial<ReplaySessionRow> = {}): ReplaySessionRow {
  return {
    id: 'sess-12345678abcdef',
    livekitRoomName: 'room-alpha',
    status: 'ended',
    scheduledStart: null,
    actualStart: new Date('2026-05-01T10:00:00.000Z'),
    actualEnd: new Date('2026-05-01T10:30:00.000Z'),
    createdAt: new Date('2026-05-01T09:55:00.000Z'),
    recordingUrl: 'sessions/sess-12345678abcdef/composite.mp4',
    perParticipantRecordingUrls: {},
    configSnapshot: {},
    ...overrides,
  };
}

function makeFakeFfmpegResult(chunks: Uint8Array[], exitCode = 0) {
  const queue = [...chunks];
  const body = new ReadableStream<Uint8Array>({
    pull(controller) {
      if (queue.length === 0) {
        controller.close();
        return;
      }
      controller.enqueue(queue.shift());
    },
  });
  return {
    body,
    done: Promise.resolve(exitCode),
    stderr: Promise.resolve(''),
  };
}

describe('GET /api/sessions/[id]/exports/clips/[flagId]', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('returns 401 for an unauthenticated request and skips every downstream lookup', async () => {
    authMock.mockResolvedValue(null);
    const { GET } = await importRoute();
    const res = await GET(new Request('http://localhost/x'), makeContext('sess-1', 'flag-1'));
    expect(res.status).toBe(401);
    expect(scopedSessionsFindByIdMock).not.toHaveBeenCalled();
    expect(findSessionFlagByIdMock).not.toHaveBeenCalled();
    expect(findSessionForReplayMock).not.toHaveBeenCalled();
    expect(signGetUrlMock).not.toHaveBeenCalled();
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 404 when the session belongs to another org (scopedDb gate rejects before any flag read)', async () => {
    // Tenancy must reject the request before `findSessionFlagById` runs.
    // Otherwise the unscoped flag lookup leaks a row from another tenant
    // even though the per-session check would later 404 — the read itself
    // is the exposure surface.
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(null);
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );
    expect(res.status).toBe(404);
    expect(findSessionFlagByIdMock).not.toHaveBeenCalled();
    expect(findSessionForReplayMock).not.toHaveBeenCalled();
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 404 when the flag is unknown', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(null);
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-missing'),
    );
    expect(res.status).toBe(404);
    expect(findSessionForReplayMock).not.toHaveBeenCalled();
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 404 when the flag belongs to a different session (cross-session smuggling guard)', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(makeFlag({ sessionId: 'sess-OTHER-9999' }));
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );
    expect(res.status).toBe(404);
    expect(findSessionForReplayMock).not.toHaveBeenCalled();
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 404 when the session itself is missing', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(makeFlag());
    findSessionForReplayMock.mockResolvedValue(null);
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );
    expect(res.status).toBe(404);
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 422 when the session never started (no actual_start)', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(makeFlag());
    findSessionForReplayMock.mockResolvedValue(makeSession({ actualStart: null, actualEnd: null }));
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );
    expect(res.status).toBe(422);
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 422 when the composite recording has not been written yet', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(makeFlag());
    findSessionForReplayMock.mockResolvedValue(makeSession({ recordingUrl: null }));
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );
    expect(res.status).toBe(422);
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 503 when R2 is not configured for this deployment', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(makeFlag());
    findSessionForReplayMock.mockResolvedValue(makeSession());
    signGetUrlMock.mockRejectedValue(new FakeR2NotConfiguredError());
    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );
    expect(res.status).toBe(503);
    expect(spawnFfmpegClipStreamMock).not.toHaveBeenCalled();
  });

  it('returns 200 streaming audio/mpeg with an attachment filename + the right ffmpeg window', async () => {
    authMock.mockResolvedValue({ user: { id: 'user-1', email: 'r@example.com' } });
    scopedSessionsFindByIdMock.mockResolvedValue(makeScopedSession());
    findSessionFlagByIdMock.mockResolvedValue(makeFlag());
    findSessionForReplayMock.mockResolvedValue(makeSession());
    signGetUrlMock.mockResolvedValue('https://r2.example.com/signed-recording.mp4?sig=abc');
    const fakeMp3 = new Uint8Array([0x49, 0x44, 0x33, 0x04, 0x00]);
    spawnFfmpegClipStreamMock.mockReturnValue(makeFakeFfmpegResult([fakeMp3]));

    const { GET } = await importRoute();
    const res = await GET(
      new Request('http://localhost/x'),
      makeContext('sess-12345678abcdef', 'flag-12345678abcdef'),
    );

    expect(res.status).toBe(200);
    expect(res.headers.get('content-type')).toBe('audio/mpeg');
    const cd = res.headers.get('content-disposition');
    expect(cd).toMatch(/^attachment; filename="clip-room-alpha-flag-123-/);
    expect(cd?.endsWith('.mp3"')).toBe(true);

    // Signed input URL was used as ffmpeg input — never the raw R2 key.
    expect(signGetUrlMock).toHaveBeenCalledWith(
      'sessions/sess-12345678abcdef/composite.mp4',
      expect.any(Number),
    );
    expect(spawnFfmpegClipStreamMock).toHaveBeenCalledOnce();
    const spawnArgs = spawnFfmpegClipStreamMock.mock.calls[0]?.[0];
    expect(spawnArgs?.inputUrl).toBe('https://r2.example.com/signed-recording.mp4?sig=abc');
    // Flag is 90s after session start; default pad is 15 → start at 75s,
    // duration 30s. Pins the windowing math at the route boundary.
    expect(spawnArgs?.window.startSec).toBeCloseTo(75);
    expect(spawnArgs?.window.durationSec).toBe(30);

    // Body actually streams the ffmpeg bytes.
    const body = await res.arrayBuffer();
    expect(new Uint8Array(body)).toEqual(fakeMp3);
  });
});
