/**
 * Smoke tests for the replay timeline component.
 *
 * The geometry math (tsToX / xToTs) is fully exercised by these
 * tests via direct queries on the rendered SVG — every utterance,
 * decision, and flag gets a `data-testid` so we can assert presence,
 * order, and per-element attributes (fill color for source palette,
 * stroke width for selected state, etc.) without scraping pixel
 * coordinates from layout.
 *
 * Wheel pan/zoom is exercised at the smoke level: we dispatch wheel
 * events and assert the view range mutates (a tick label that was
 * present at full zoom is no longer present after zooming in). The
 * exact target-fraction math isn't worth pinning — that's the kind
 * of detail that makes tests brittle when we tune feel.
 */

import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';

import { ReplayTimeline } from './replay-timeline';

import type {
  ReplayDecisionDTO,
  ReplayFlagDTO,
  ReplayParticipantDTO,
  ReplaySessionDTO,
  ReplayUtteranceDTO,
} from './replay-types';

const SESSION: ReplaySessionDTO = {
  id: 'sess-1',
  livekit_room_name: 'room-1',
  status: 'ended',
  scheduled_start: null,
  actual_start: '2026-05-01T10:00:00.000Z',
  actual_end: '2026-05-01T10:10:00.000Z',
  created_at: '2026-05-01T09:55:00.000Z',
  has_composite_recording: true,
  participant_recording_identities: ['alice-001'],
};

const ALICE: ReplayParticipantDTO = {
  id: 'p-alice',
  display_name: 'Alice',
  livekit_identity: 'alice-001',
  role: 'participant',
  joined_at: '2026-05-01T10:00:05.000Z',
  left_at: '2026-05-01T10:09:55.000Z',
};

const BOB: ReplayParticipantDTO = {
  id: 'p-bob',
  display_name: 'Bob',
  livekit_identity: 'bob-002',
  role: 'participant',
  joined_at: '2026-05-01T10:00:08.000Z',
  left_at: '2026-05-01T10:09:50.000Z',
};

function makeUtterance(
  id: string,
  participant: ReplayParticipantDTO,
  startOffsetSec: number,
  durationSec: number,
): ReplayUtteranceDTO {
  const startMs = Date.parse(SESSION.actual_start!) + startOffsetSec * 1000;
  return {
    id,
    participant_id: participant.id,
    participant_identity: participant.livekit_identity,
    participant_display_name: participant.display_name,
    text: `text-${id}`,
    is_final: true,
    confidence: 0.95,
    start_ts: new Date(startMs).toISOString(),
    end_ts: new Date(startMs + durationSec * 1000).toISOString(),
  };
}

function makeDecision(
  id: string,
  offsetSec: number,
  overrides: Partial<ReplayDecisionDTO> = {},
): ReplayDecisionDTO {
  const ts = new Date(Date.parse(SESSION.actual_start!) + offsetSec * 1000).toISOString();
  return {
    id,
    tick_id: offsetSec * 2,
    ts,
    action: 'prompt_participant',
    target_participant_id: null,
    source: 'rules_engine',
    triggering_rule: 'silence_gap',
    researcher_id: null,
    researcher_hint: null,
    reason_codes: ['silence_gap'],
    reason_human: 'long quiet stretch',
    confidence: 0.7,
    suppressed_by: [],
    was_executed: true,
    llm_prompt: null,
    llm_output: null,
    tts_audio_url: null,
    spoken_at: ts,
    cooldown_until: ts,
    ...overrides,
  };
}

function makeFlag(id: string, offsetSec: number, autoGenerated = false): ReplayFlagDTO {
  return {
    id,
    ts: new Date(Date.parse(SESSION.actual_start!) + offsetSec * 1000).toISOString(),
    researcher_id: autoGenerated ? null : 'r-1',
    note: autoGenerated ? null : `bookmark-${id}`,
    auto_generated: autoGenerated,
  };
}

interface RenderOptions {
  participants?: ReplayParticipantDTO[];
  utterances?: ReplayUtteranceDTO[];
  decisions?: ReplayDecisionDTO[];
  flags?: ReplayFlagDTO[];
  currentTs?: string;
  selectedDecisionId?: string | null;
  onSeek?: (ts: string) => void;
  onSelectDecision?: (id: string) => void;
}

function renderTimeline(opts: RenderOptions = {}) {
  const onSeek = opts.onSeek ?? vi.fn();
  const onSelectDecision = opts.onSelectDecision ?? vi.fn();
  const utils = render(
    <ReplayTimeline
      session={SESSION}
      participants={opts.participants ?? [ALICE, BOB]}
      utterances={opts.utterances ?? []}
      decisions={opts.decisions ?? []}
      flags={opts.flags ?? []}
      currentTs={opts.currentTs ?? SESSION.actual_start!}
      selectedDecisionId={opts.selectedDecisionId ?? null}
      onSeek={onSeek}
      onSelectDecision={onSelectDecision}
    />,
  );
  return { ...utils, onSeek, onSelectDecision };
}

describe('<ReplayTimeline />', () => {
  it('renders one speech band per participant', () => {
    renderTimeline({ participants: [ALICE, BOB] });

    expect(screen.getByTestId(`replay-timeline-band-${ALICE.id}`)).toBeInTheDocument();
    expect(screen.getByTestId(`replay-timeline-band-${BOB.id}`)).toBeInTheDocument();
  });

  it('renders a rect for every utterance, scoped to its participant', () => {
    renderTimeline({
      utterances: [
        makeUtterance('u-1', ALICE, 5, 3),
        makeUtterance('u-2', ALICE, 20, 4),
        makeUtterance('u-3', BOB, 10, 2),
      ],
    });

    expect(screen.getByTestId('replay-timeline-utterance-u-1')).toBeInTheDocument();
    expect(screen.getByTestId('replay-timeline-utterance-u-2')).toBeInTheDocument();
    expect(screen.getByTestId('replay-timeline-utterance-u-3')).toBeInTheDocument();
  });

  it('renders one decision marker per decision', () => {
    renderTimeline({
      decisions: [makeDecision('d-1', 10), makeDecision('d-2', 30), makeDecision('d-3', 90)],
    });

    expect(screen.getByTestId('replay-timeline-decision-d-1')).toBeInTheDocument();
    expect(screen.getByTestId('replay-timeline-decision-d-2')).toBeInTheDocument();
    expect(screen.getByTestId('replay-timeline-decision-d-3')).toBeInTheDocument();
  });

  it('renders one flag marker per flag', () => {
    renderTimeline({
      flags: [makeFlag('f-1', 15), makeFlag('f-2', 45, true)],
    });

    expect(screen.getByTestId('replay-timeline-flag-f-1')).toBeInTheDocument();
    expect(screen.getByTestId('replay-timeline-flag-f-2')).toBeInTheDocument();
  });

  it('colors decision markers by source (rules_engine vs researcher_manual vs researcher_whisper)', () => {
    renderTimeline({
      decisions: [
        makeDecision('rules', 10, { source: 'rules_engine' }),
        makeDecision('manual', 30, { source: 'researcher_manual' }),
        makeDecision('whisper', 60, { source: 'researcher_whisper' }),
      ],
    });

    expect(screen.getByTestId('replay-timeline-decision-rules')).toHaveAttribute(
      'data-source',
      'rules_engine',
    );
    expect(screen.getByTestId('replay-timeline-decision-manual')).toHaveAttribute(
      'data-source',
      'researcher_manual',
    );
    expect(screen.getByTestId('replay-timeline-decision-whisper')).toHaveAttribute(
      'data-source',
      'researcher_whisper',
    );

    const rulesCircle = screen
      .getByTestId('replay-timeline-decision-rules')
      .querySelector('circle');
    const manualCircle = screen
      .getByTestId('replay-timeline-decision-manual')
      .querySelector('circle');
    const whisperCircle = screen
      .getByTestId('replay-timeline-decision-whisper')
      .querySelector('circle');

    expect(rulesCircle?.getAttribute('stroke')).not.toEqual(manualCircle?.getAttribute('stroke'));
    expect(manualCircle?.getAttribute('stroke')).not.toEqual(whisperCircle?.getAttribute('stroke'));
  });

  it('outlines the selected decision marker so the researcher can see what is open in the detail pane', () => {
    renderTimeline({
      decisions: [makeDecision('d-1', 10), makeDecision('d-2', 30)],
      selectedDecisionId: 'd-2',
    });

    const selected = screen.getByTestId('replay-timeline-decision-d-2');
    const unselected = screen.getByTestId('replay-timeline-decision-d-1');

    // Selected marker draws an additional dashed-outline circle.
    expect(selected.querySelectorAll('circle')).toHaveLength(2);
    expect(unselected.querySelectorAll('circle')).toHaveLength(1);
  });

  it('clicking a decision marker calls onSelectDecision AND onSeek to the decision ts', () => {
    const onSeek = vi.fn();
    const onSelectDecision = vi.fn();
    const decision = makeDecision('d-1', 42);
    renderTimeline({
      decisions: [decision],
      onSeek,
      onSelectDecision,
    });

    fireEvent.click(screen.getByTestId('replay-timeline-decision-d-1'));

    expect(onSelectDecision).toHaveBeenCalledTimes(1);
    expect(onSelectDecision).toHaveBeenCalledWith('d-1');
    expect(onSeek).toHaveBeenCalledTimes(1);
    expect(onSeek).toHaveBeenCalledWith(decision.ts);
  });

  it('clicking a flag marker calls onSeek to the flag ts (no decision selection)', () => {
    const onSeek = vi.fn();
    const onSelectDecision = vi.fn();
    const flag = makeFlag('f-1', 33);
    renderTimeline({ flags: [flag], onSeek, onSelectDecision });

    fireEvent.click(screen.getByTestId('replay-timeline-flag-f-1'));

    expect(onSeek).toHaveBeenCalledTimes(1);
    expect(onSeek).toHaveBeenCalledWith(flag.ts);
    expect(onSelectDecision).not.toHaveBeenCalled();
  });

  it('renders the scrubber cursor on top of everything', () => {
    renderTimeline({ currentTs: SESSION.actual_start! });
    expect(screen.getByTestId('replay-timeline-cursor')).toBeInTheDocument();
  });

  it('shows a tooltip on decision hover and clears it on mouse leave', () => {
    renderTimeline({ decisions: [makeDecision('d-1', 10)] });

    expect(screen.queryByTestId('replay-timeline-tooltip')).not.toBeInTheDocument();

    fireEvent.mouseEnter(screen.getByTestId('replay-timeline-decision-d-1'));
    expect(screen.getByTestId('replay-timeline-tooltip')).toBeInTheDocument();

    fireEvent.mouseLeave(screen.getByTestId('replay-timeline-decision-d-1'));
    expect(screen.queryByTestId('replay-timeline-tooltip')).not.toBeInTheDocument();
  });

  it('shows a tooltip on utterance hover with the participant name + transcript snippet', () => {
    renderTimeline({ utterances: [makeUtterance('u-1', ALICE, 5, 3)] });

    fireEvent.mouseEnter(screen.getByTestId('replay-timeline-utterance-u-1'));

    const tooltip = screen.getByTestId('replay-timeline-tooltip');
    expect(tooltip).toHaveTextContent(/Alice/);
    expect(tooltip).toHaveTextContent('text-u-1');
  });

  it('falls back to placeholder lanes when the participant roster is empty', () => {
    // Empty session — render shouldn't crash, the decision + flag
    // lanes still draw so the layout doesn't reflow when participants
    // join in a later replay.
    renderTimeline({ participants: [] });

    expect(screen.getByTestId('replay-timeline-svg')).toBeInTheDocument();
    expect(screen.getByTestId('replay-timeline-cursor')).toBeInTheDocument();
  });

  it('renders interactive decisions even when the participant roster is empty', () => {
    // Edge case: a session that ended before anyone joined can still
    // have rule_engine `stay_silent` decisions logged. The timeline
    // must surface those so the audit trail isn't blank.
    renderTimeline({ participants: [], decisions: [makeDecision('d-only', 10)] });

    expect(screen.getByTestId('replay-timeline-decision-d-only')).toBeInTheDocument();
  });
});
